blogshop/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('createpost/', views.createpost, name='createpost'),
    path('postsconfig/', views.postsconfig, name='postsconfig'),
    path('editpost/<int:post_id>', views.editpost, name='editpost'),
]

blogshop/mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.main_page, name='main_page')
]

blogshop/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('register', views.register, name='register'),
    path('profile/', include([
        path('', views.own_profile, name='own_profile'),
        path('<slug:slug>/', include([
            path('', views.profile, name='profile'),
            path('subscribers/', views.subscribers, name='subscribers'),
            path('subscribed/', views.subscribed, name='subscribed'),
        ])),
    ]))
]

blogshop/blog/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    product = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2,
                                max_digits=10)
    quantity = models.IntegerField()
    avaible = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.product

blogshop/mainpage/models.py
from django.db import models

# Create your models here.

blogshop/users/models.py
from django.db import models
from django.conf import settings 
from django.utils.text import slugify

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    profileimg = models.ImageField(upload_to='avatars/', blank=True, null=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.slug: 
            self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

class Subscription(models.Model):
    subscriber  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='subscriber')
    subscribed_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='subscribed_to')
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['subscriber', 'subscribed_to'], name='unique_subscription')
        ]

blogshop/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.forms.widgets import Textarea

class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profileimg', 'description']
        widgets = {
            'description': Textarea()
        }

blogshop/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CreatePostForm, ConfigPostForm
from .models import Post
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

@login_required
def postsconfig(request):
    posts = Post.objects.filter(seller=request.user)
    forms = [ConfigPostForm(instance=post) for post in posts]
    return render(request,'blog/postsconfig.html', {
        'forms': forms,
    })

@login_required
def createpost(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.seller = request.user
            post.save()
            return redirect('blog:postsconfig')
    form = CreatePostForm()
    return render(request, 'blog/createpost.html',{
        'form': form,
    })
    
@login_required
@require_POST
def editpost(requset, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = ConfigPostForm(requset.POST, instance=post)
    if form.is_valid():
        form.save()
    return redirect('blog:postsconfig')

blogshop/mainpage/views.py
from django.shortcuts import render

def main_page(request):
    return render(request, 'mainpage/recommendations.html')

blogshop/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserCreationForm, ProfileForm
from .models import Profile, Subscription
from django.urls import reverse

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {
        'form': form,
    })

def own_profile(request):
    return redirect(reverse('users:profile', args=[request.user.profile.slug]))
             
def profile(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    if request.user.is_authenticated:
        if profile.user == request.user:
            if request.method == 'POST':
                if not request.POST.get('Subscribe'):
                    form = ProfileForm(request.POST, request.FILES, instance=profile)
                    if form.is_valid():
                        form.save()
        else:
            if request.method == 'POST':
                if not Subscription.objects.filter(subscriber=request.user, subscribed_to=profile.user):
                    subscription = Subscription.objects.create(subscriber=request.user, subscribed_to=profile.user)
                    subscription.save()
    return render(request, 'users/profile/mainprofile.html', {
        'profile': profile,
    })

def settings(request):
    if request.user.is_authenticated:
        form = ProfileForm(instance=request.user.profile)
        return render(request, 'settings.html', {
            'form': form,
        })
    return redirect('login')

def subscribers(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    return render(request, 'users/profile/profilesubscribers.html', {
        'profile': profile,
    })

def subscribed(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    return render(request, 'users/profile/profilesubscribed.html', {
        'profile': profile,
    })

blogshop/blog/templates/blog/createpost.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    CreatePost
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="Create Post" class="button-submit">
    </form>
{% endblock content %}

blogshop/blog/templates/blog/postsconfig.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    profileconfig
{% endblock title %}

{% block content %}
    {% for form in forms %}
    <form action="{% url 'blog:editpost' form.instance.id %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Edit" class="button-submit">
    </form>
    {% endfor %} 
{% endblock content %}

blogshop/mainpage/templates/mainpage/recommendations.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Recommendations
{% endblock title %}

{% block content %}
<h1>hello</h1>
{% endblock content %}

blogshop/users/templates/settings.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Settings
{% endblock title %}

{% block content %}
    <a href="{% url 'blog:createpost' %}">Craeate Post</a>
    <a href="{% url 'blog:postsconfig' %}">Config posts</a>
    <form action="{% url 'users:profile' user.profile.slug %}" method="post" enctype="multipart/form-data">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Change settings" class="button-submit">
    </form>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout" class="button-submit">
    </form>
{% endblock content %}

blogshop/users/templates/users/profile.html
{% load static %}
<div class="profile">
    <img src="{% if profile.profileimg %}
        {{profile.profileimg.url}}
    {% else %}
        {% static 'img/profile-icon.jpg' %}
    {% endif %}" alt="" class="avatar">
    <div class="username">
        {{profile.user}}
    </div>
    <div class="subscription-stat">
        <a href="{% url 'users:subscribers' profile.slug %}" class="reg-a">Subscribers: <span class="subscription-stat-nums">{{profile.user.subscribed_to.all.count}}</span></a>
         <a href="{% url 'users:subscribed' profile.slug %}" class="reg-a">Subscribed:<span class="subscription-stat-nums">{{profile.user.subscriber.all.count}}</span></a>
    </div>
    <form action="{% url 'users:profile' profile.slug %}" method="post">
        {% csrf_token %}
        <input type="submit" class="button-submit" value="Subscribe" name="Subscribe">
    </form>
    <div class="NF">
        {{profile.user.first_name}} {{profile.user.last_name}}
    </div>
    <div class="description">
        {% if profile.description %}
            {{profile.description}}
        {% endif %}
    </div>
</div>