BlogShop/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('createpost/', views.createpost, name='createpost'),
    path('postsconfig/', views.postsconfig, name='postsconfig'),
    path('editpost/<int:post_id>', views.editpost, name='editpost'),
    path('postdetail/<int:id>/<slug:slug>/', views.postdetail, name='postdetail'),
    path('postdelete/<int:post_id>/', views.postdelete, name='postdelete')
]

BlogShop/blog/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True)

    def get_absolute_url(self):
        return reverse('mainpage:recommendations_by_category', args=[self.slug])

    def __str__(self):
        return self.name

class Post(models.Model):
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    product = models.CharField(max_length=50, blank=False, null=False)
    slug = models.SlugField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts/', null=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2,
                                max_digits=10)
    quantity = models.IntegerField()
    avaible = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.product)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.product

    def get_absolute_url(self):
        return reverse('blog:postdetail', args=[self.id, self.slug])   

BlogShop/blog/forms.py
from django import forms
from .models import Post

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['created', 'updated', 'seller', 'slug', 'avaible']

class ConfigPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['created', 'updated', 'seller', 'slug']

BlogShop/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CreatePostForm, ConfigPostForm
from .models import Post
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from users.models import Profile
from django.utils.text import slugify
from users.views import check_is_subscribed

@login_required
def postsconfig(request):
    posts = Post.objects.filter(seller=request.user)
    forms = [ConfigPostForm(instance=post) for post in posts]
    return render(request,'blog/postsconfig.html', {
        'forms': forms,
    })

@login_required
def createpost(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.seller = request.user
            post.save()
            return redirect('blog:postsconfig')
    form = CreatePostForm()
    return render(request, 'blog/createpost.html',{
        'form': form,
    })
    
@login_required
@require_POST
def editpost(requset, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = ConfigPostForm(requset.POST, requset.FILES, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.slug = slugify(post.product)
        post.save()
    return redirect('blog:postsconfig')

def postdetail(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    profile = get_object_or_404(Profile, user=post.seller)
    is_subscribed = check_is_subscribed(request.user, profile.user)
    return render(request, 'blog/postdetail.html', {
        'post': post,
        'profile': profile,
        'is_subscribed': is_subscribed,
    })

@login_required
@require_POST
def postdelete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect('blog:postsconfig')

BlogShop/blog/templates/blog/createpost.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    CreatePost
{% endblock title %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="Create Post" class="button-submit">
    </form>
{% endblock content %}

BlogShop/blog/templates/blog/postdetail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{post}}
{% endblock title %}

{% block content %}
    <div class="post-title">{{post.product}}</div>
    <a href="{{post.category.get_absolute_url}}" class="post-category">{{post.category}}</a>
    {% if post.image%}<img src={{post.image.url}} class="post-image">{% endif %}
    <div class="post-description">{{post.description}}</div>
    <div class="post-price">{{post.price}}$</div>
    <div class="post-quantity">Quantity:{{post.quantity}}</div>
    {% include 'users/profile.html' %}
{% endblock content %}

BlogShop/blog/templates/blog/postsconfig.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    profileconfig
{% endblock title %}

{% block content %}
    <a href="{% url 'blog:createpost' %}" class="button-submit">Craeate Post</a>
    {% for form in forms %}
    <form action="{% url 'blog:editpost' form.instance.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Edit" class="button-submit">
    </form>
    <form action="{% url 'blog:postdelete' form.instance.id%}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="button-delete">
    </form>
    {% endfor %} 
{% endblock content %}