BlogShop/BlogShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path("payment/", include('payment.urls', namespace='payment')),
    path('', include('mainpage.urls', namespace='main_page')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BlogShop/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('createpost/', views.createpost, name='createpost'),
    path('postsconfig/', views.postsconfig, name='postsconfig'),
    path('editpost/<int:post_id>', views.editpost, name='editpost'),
    path('postdetail/<int:id>/<slug:slug>/', views.postdetail, name='postdetail'),
    path('postdelete/<int:post_id>/', views.postdelete, name='postdelete')
]

BlogShop/payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('topupbalance/', views.topupbalanceview, name='topupbalance'),
    path('success/', views.success, name='success'),
    path('cancel/', views.cancel, name='cancel'),
    path('webhook/', webhooks.stripe_webhook, name='stripe_webhook'),
]

BlogShop/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('register', views.register, name='register'),
    path('profile/', include([
        path('', views.own_profile, name='own_profile'),
        path('<slug:slug>/', include([
            path('', views.profile, name='profile'),
            path('subscribers/', views.subscribers, name='subscribers'),
            path('subscribed/', views.subscribed, name='subscribed'),
            path('subscribe/', views.subscribe, name='subscribe')
        ])),
    ]))
]

BlogShop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}BlogShop{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header class="header">
        <div class="container-header">
            <div class="home-box">
                <a href="/" class="home-link a-header">
                    <img src="{% static 'img/home.png' %}" alt="" class="home-img">Home
                </a>
            </div>
            <div class="user-box">
            {% if user.is_authenticated %}
                <div>
                    <a href="{% url 'payment:topupbalance' %}" class="a-header">
                        {{user.balance.balance}}$
                    </a>
                </div>
                <a href="{% url 'users:profile' user.profile.slug %}" class="user-link a-header">
                    {{ user }}
                <img src="{% if user.profile.profileimg %}
                    {{user.profile.profileimg.url}}
                {% else %}
                    {% static 'img/profile-icon.jpg' %}
                {% endif %}" alt="" class="avatar">
                </a>
                <div class="gear">
                    <a href="{% url 'users:settings' %}" class="gear">
                        <img src="{% static 'img/gear_PNG48.png' %}" alt="" class="gear-img">
                    </a>
                </div>
            {% else %}
                <a href="{% url "login" %}" class="user-link a-header">Login</a>
            {% endif %}
            </div>
        </div>
    </header>
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>