BlogShop/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('register', views.register, name='register'),
    path('profile/', include([
        path('', views.own_profile, name='own_profile'),
        path('<slug:slug>/', include([
            path('', views.profile, name='profile'),
            path('subscribers/', views.subscribers, name='subscribers'),
            path('subscribed/', views.subscribed, name='subscribed'),
            path('subscribe/', views.subscribe, name='subscribe')
        ])),
    ]))
]

BlogShop/users/models.py
from django.db import models
from django.conf import settings 
from django.utils.text import slugify

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    profileimg = models.ImageField(upload_to='avatars/', blank=True, null=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.slug: 
            self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username

class Subscription(models.Model):
    subscriber  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='subscriber')
    subscribed_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='subscribed_to')
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['subscriber', 'subscribed_to'], name='unique_subscription')
        ]

BlogShop/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .forms import UserCreationForm, ProfileForm
from .models import Profile, Subscription
from django.urls import reverse
from blog.models import Post

def check_is_subscribed(subscriber, subscribed_to):
    if Subscription.objects.filter(subscriber=subscriber, subscribed_to=subscribed_to):
        return True
    return False
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {
        'form': form,
    })

def own_profile(request):
    return redirect(reverse('users:profile', args=[request.user.profile.slug]))
             
def profile(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    posts = Post.objects.filter(avaible=True, seller=profile.user)
    is_subscribed = check_is_subscribed(request.user, profile.user)
    if request.user.is_authenticated:
        if profile.user == request.user:
            if request.method == 'POST':
                form = ProfileForm(request.POST, request.FILES, instance=profile)
                if form.is_valid():
                    form.save()
    return render(request, 'users/profile/mainprofile.html', {
        'profile': profile,
        'posts': posts,
        'is_subscribed': is_subscribed,
    })

def settings(request):
    if request.user.is_authenticated:
        form = ProfileForm(instance=request.user.profile)
        return render(request, 'settings.html', {
            'form': form,
        })
    return redirect('login')

def subscribers(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    is_subscribed = check_is_subscribed(request.user, profile.user)
    return render(request, 'users/profile/profilesubscribers.html', {
        'profile': profile,
        'is_subscribed': is_subscribed,
    })

def subscribed(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    is_subscribed = check_is_subscribed(request.user, profile.user)
    return render(request, 'users/profile/profilesubscribed.html', {
        'profile': profile,
        'is_subscribed': is_subscribed,
    })

@require_POST
@login_required
def subscribe(request, slug):
    profile = get_object_or_404(Profile, slug=slug)
    if not Subscription.objects.filter(subscriber=request.user, subscribed_to=profile.user):
        subscription = Subscription.objects.create(subscriber=request.user, subscribed_to=profile.user)
        subscription.save()
    else:
        subscription = get_object_or_404(Subscription, subscriber=request.user, subscribed_to=profile.user)
        subscription.delete()
    return redirect(reverse('users:profile', args=[profile.slug]))

BlogShop/users/templates/settings.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Settings
{% endblock title %}

{% block content %}
    <a href="{% url 'blog:createpost' %}" class="button-submit">Craeate Post</a>
    <a href="{% url 'blog:postsconfig' %}" class="button-submit">Config posts</a>
    <a href="{% url 'payment:topupbalance' %}" class="button-submit">Top Up Balance</a>
    <form action="{% url 'users:profile' user.profile.slug %}" method="post" enctype="multipart/form-data">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Change settings" class="button-submit">
    </form>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout" class="button-submit">
    </form>
{% endblock content %}

BlogShop/users/templates/users/profile.html
{% load static %}
<a href="{% url 'users:profile' profile.slug %}" class="profile-a">
    <div class="profile">
        <img src="{% if profile.profileimg %}
            {{profile.profileimg.url}}
        {% else %}
            {% static 'img/profile-icon.jpg' %}
        {% endif %}" alt="" class="avatar">
        <div class="username">
            {{profile.user}}
        </div>
        <div class="subscription-stat">
            <a href="{% url 'users:subscribers' profile.slug %}" class="reg-a">Subscribers: <span class="subscription-stat-nums">{{profile.user.subscribed_to.all.count}}</span></a>
            <a href="{% url 'users:subscribed' profile.slug %}" class="reg-a">Subscribed:<span class="subscription-stat-nums">{{profile.user.subscriber.all.count}}</span></a>
        </div>
        <form action="{% url 'users:subscribe' profile.slug %}" method="post">
            {% csrf_token %}
            <input type="submit" class="{% if is_subscribed %}button-delete{% else %}button-submit{% endif %}"
             value="{% if is_subscribed %} Unsubscribe {% else %} Subscribe{% endif %}">
        </form>
        <div class="NF">
            {{profile.user.first_name}} {{profile.user.last_name}}
        </div>
        <div class="description">
            {% if profile.description %}
                {{profile.description}}
            {% endif %}
        </div>
    </div>
</a class="profile-a">

BlogShop/users/templates/users/profile/mainprofile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{user}}
{% endblock title %}

{% block content %}
    <ul>
        {% for post in posts %}
            <li class="profile-post">
                <a href={{post.get_absolute_url}}>
                    <div class="profile-post-title">{{post.product}}</div>
                    {% if post.image %}<div><img src={{post.image.url}} class="profile-post-image"></div>{% endif %}
                    <div class="profile-post-price">{{post.price}}$</div>
                    </a>
            </li>
        {% endfor %}
    </ul>
    {% include "users/profile.html" %}
{% endblock content %}

BlogShop/users/templates/users/profile/profilesubscribed.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <ul>
        {% for subscription in profile.user.subscriber.all %}
            <li>
                <a href="{% url 'users:profile' subscription.subscribed_to.profile.slug %}" class="subscription">
                    {{subscription.subscribed_to.username}} 
                    <img src="
                    {% if subscription.subscribed_to.profile.profileimg %}
                        {{subscription.subscribed_to.profile.profileimg.url}}
                    {% else %}
                        {% static 'img/profile-icon.jpg' %}
                    {% endif %}" class="subscription-img">
                </a>
            </li>
        {% endfor %}
    </ul>
    {% include "users/profile.html" %}
{% endblock content %}

BlogShop/users/templates/users/profile/profilesubscribers.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <ul>
        {% for subscription in profile.user.subscribed_to.all %}
            <li>
                <a href="{% url 'users:profile' subscription.subscriber.profile.slug %}" class="subscription">
                    {{subscription.subscriber.username}}
                    <img src="
                    {% if subscription.subscriber.profile.profileimg %}
                        {{subscription.subscriber.profile.profileimg.url}}
                    {% else %}
                        {% static 'img/profile-icon.jpg' %}
                    {% endif %}" class="subscription-img">
                </a>
            </li>
        {% endfor %}
    </ul>
    {% include "users/profile.html" %}
{% endblock content %}